### ISSUE TITLE
Setup the project so it's easy to develop and test this nextjs library

### ISSUE THREAD

**Issue by frouo** [frouo/next-markdown#6]
Please, help.

## Problem

Right now I have no proper solution:
- I tried to use `npm link` but, for every changes in `next-markdown/src/index.ts`, I need to execute `cd examples/blogging && rm -rf node_modules/next-markdown && npm link`. Very painful.
- copy/paste `next-markdown/src/index.ts` and use it locally in an example, so when I am done, I copy/paste back to `next-markdown/src`. Very painful and ugly...
- I cannot write tests. I tried exporting a `next-markdown` function (eg. `export getNextmdFromFilePath = (..)=>{..}`) but `import { getNextmdFromFilePath } from '../';` in file `__tests__/index.test.ts` failed with error `Module '"../index"' has no exported member 'getNextmdFromFilePath'`

## Wanted

I don't have the time (and knowledge yet) to setup properly the project this way:

- ability to write tests...
- live test: everytime `next-markdown/src/index.ts` changes, tests are ran
- dev mode with lie reloading: having a project where everytime `next-markdown/src/index.ts` changes, the project updates
- code splitting. For now if I create for example an utility file `next-markdown/src/utility.ts` the published npm library does not work (module not found)

## Thank you

Any help is much than appreciated 🙏

**Comment by edvincandon** [comment]
on it daaaawg 🐕

**Comment by edvincandon** [comment]
all done - running tests on each change is kind of overkill.
Setting up some pre-push githooks might be a better solution.

**Comment by frouo** [comment]
Re-opened: NPM published package once installed in the project is not working (with error `Error: Directory import '/Users/frouo/Programming/Lembot/app/node_modules/next-markdown/dist/utils' is not
supported resolving ES modules imported from/Users/frouo/Programming/Lembot/app/node_modules/next-
markdown/dist/index.is` cf. screenshot below).

Attempted to fix this with #10 & #11 but where it fixes something here and breaks somewhere else...

![IMG_6045](https://user-images.githubusercontent.com/2499356/161034806-9e04791b-d154-4e30-803d-5829f0f3546d.png)
